### ISSUE TITLE
BUG: fba bug

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#190] opened 2016-11-07 20:13 UTC
iBioSim Version 2.8.3

Operating system: Windows 8.1

Bug reported by: calliclark24@gmail.com

Description:
example fba model created from sbml code throws error

Stack trace:
java.lang.NullPointerException
	at analysis.fba.FluxBalanceAnalysis.PerformFluxBalanceAnalysis(FluxBalanceAnalysis.java:77)
	at analysis.main.Run.execute(Run.java:527)
	at analysis.main.AnalysisView.run(AnalysisView.java:1114)
	at analysis.main.AnalysisThread.run(AnalysisThread.java:24)

**Comment by leandrohw** [comment] 2017-04-01 00:34
Can't reproduce this one. I have ran FBA on several models and none caused any error. Closing this one.

**Closed by leandrohw** 2017-04-01 00:34 UTC
Labels: BUG, Needs Testing
