### ISSUE TITLE
Learn view created on Windows does not show on Mac

### ISSUE THREAD

**Issue by zgzn** [MyersResearchGroup/iBioSim#272] opened 2017-03-25 20:20 UTC
My student created the attached model with learn view on Win 10, but I could not see it on my Mac (OS X Yosemite v10.10.5). Only SBML models are visible. 
[learnmodel.zip](https://github.com/MyersResearchGroup/iBioSim/files/870342/learnmodel.zip)

**Comment by leandrohw** [comment] 2017-03-26 22:06
The learn view is not visible because the project doesn't have any directories. I don't know if it is because your student modified the project folder or if windows build is not creating a new directory for the learn view. Nonetheless, there are some files from the learn view such as the results (gcm and dot files).

**Comment by zgzn** [comment] 2017-03-26 23:39
Sorry, I uploaded the wrong zip file. Attached one should illustrate this issue. If you open the iBioSim project number_2 on Mac, it only shows learnmodel.xml, but not the learn view with the same name.
[number_2.zip](https://github.com/MyersResearchGroup/iBioSim/files/871157/number_2.zip)

**Comment by cjmyers** [comment] 2017-03-27 14:34
Problem is full path is showing up in the <file>.lrn files for the model and all data files.  This may be a Windows/Mac separator issue.  Need to see if we can reproduce on Mac.

**Comment by cjmyers** [comment] 2017-07-13 23:39
Hopefully fixed with the big separator bug fix.

**Closed by cjmyers** 2017-07-13 23:39 UTC
Labels: BUG
