### ISSUE TITLE
BUG: adding a promoter as a reactant/product/modifier of regular reaction causes problem

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#182] opened 2016-11-07 20:10 UTC
Adding a promoter into a reaction causes a problem because it does search the promoters when making the layout connection.

**Comment by leandrohw** [comment] 2017-04-10 17:34
Not sure what the issue is. Currently, promoters are not allowed to connect promoter to reaction.

**Comment by cjmyers** [comment] 2017-04-10 18:56
I think this relates to the textual view editor.

**Comment by leandrohw** [comment] 2017-04-19 17:06
I can add promoter to reaction in textual form without errors. Not sure if the problem is this shouldn't be allowed or it was throwing exceptions.

**Comment by cjmyers** [comment] 2017-07-12 15:47
Ok, will close this one.

**Closed by cjmyers** 2017-07-12 15:47 UTC
Labels: BUG, Needs Testing
