### ISSUE TITLE
I am having a variety of errors when trying to create promoters, change settings of species and save.

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#409] opened 2017-09-19 23:50 UTC
iBioSim Version 3.0.0-beta

Operating system: Mac OS X

Bug reported by: mginleyh@gmail.com

Description:
am having some troubles with ibiosim. When i try to create a promoter in the program I get the following error message: 

program has thrown an exception of error type:
java.olang.NumberFormatExcetipn: empty String

Some other things are weird as well. When I try to enter a lac species as an input that degrades I get an error that illegal values were entered.

Finally, when I try to save anything, I am not able to open it the next time I use ibiosim. I have tried both the java .jar file and the mac version with the same results.

**Comment by cjmyers** [comment] 2017-12-23 17:41
Duplicate of #410

**Closed by cjmyers** 2017-12-23 17:41 UTC
Labels: BUG
